module.exports = {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    NO_DATA: 'NO_DATA',
    NO_TABLE: 'NO_TABLE',
    NOT_ENOUGH_AUTHORITY: 'NOT_ENOUGH_AUTHORITY',
    POPULAR_ERROR: {
      INSERT_FAILED: 'INSERT_FAILED',
      RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
      UPDATE_FAILED: 'UPDATE_FAILED',
      DELETE_FAILED: 'DELETE_FAILED',
    },
  };